kevgo/text-runner

bin/cuke-cli.cmd, features/support/env.ls, src/helpers/parse-cli-args.ls, test/helpers/parse-cli-args-spec.ls
=> Fix Windows build

features/links/mailto.feature, src/activity-types/check-link.js
=> Skip mailto links

features/fast-option.feature
=> Specify fast option

features/add-command.feature, features/support/then-steps.js, src/commands/add/add-command.js, src/commands/available-commands.js, src/text-runner.js
=> Add-command

appveyor.yml, bin/coverage, documentation/built-in-activity-types.md, features/formatters/signals.feature, features/links/external-websites.feature, features/offline-option.feature, features/support/api-world.js, src/activity-types/check-image.js, src/activity-types/check-link.js, src/cli/cli-arg-types.js, src/cli/parse-cli-args-test.js, src/cli/parse-cli-args.js, src/commands/help/help-command.js, src/text-runner.js
=> Rename fast to offline

documentation/configuration.md, features/configuration-file/generate.feature, src/configuration/configuration.js
=> More detailed config

CONTRIBUTING.md, text-run/does-command-exist.js
=> Verify documented commands

features/commands/add-command.feature, src/commands/add/add-command.js
=> Better empty step template

features/formatters/signals.feature, src/formatters/detailed-formatter.js, src/formatters/dot-formatter.js, src/formatters/formatter.js
=> Prevent duplicate output of skipped steps

features/links/links-to-html-anchors.feature, src/commands/run/link-target-list-builder.js
=> Emulate Github behavior for PascalCase link targets

features/block-syntax/html-tags.feature, src/commands/run/activity-list-builder.js
=> Allow more tag types (WIP)

features/configuration-options/folder-mapping.feature, src/actions/check-link.js, src/configuration/config-file-structure.js, src/configuration/configuration.js, src/configuration/load-configuration.js, src/helpers/apply-mapping-test.js, src/helpers/apply-mapping.js, src/helpers/strip-leading-slash-test.js, src/helpers/strip-leading-slash.js
=> Folder mapping

documentation/configuration.md, features/configuration-file/generate.feature, features/configuration-options/default-file.feature, src/actions/check-link.js, src/configuration/config-file-structure.js, src/configuration/configuration.js, src/configuration/create-configuration.js, src/configuration/load-configuration.js, src/helpers/reverse-publication-test.js, src/helpers/reverse-publication.js
=> defaultFiles option

features/support/env.ts
This is needed for the retries to work.
=> Async rimraf

CHANGELOG.md, features/actions/unknown.feature, features/commands/scaffold-command.feature, src/actions/action-finder.ts, src/commands/available-commands.ts, src/commands/help.ts, src/commands/scaffold.ts, src/text-runner.ts
=> Rename add command to scaffold

text-runner/tsconfig-build.json, text-runner/tsconfig.json, textrun-npm/tsconfig.json
=> Compile only TS files

text-runner/features/actions/custom/skipping.feature, text-runner/features/commands/scaffold-command.feature, text-runner/src/actions/built-in/append-file.ts, text-runner/src/actions/built-in/cd.ts, text-runner/src/actions/built-in/check-image.ts, text-runner/src/actions/built-in/check-link.ts, text-runner/src/actions/built-in/create-directory.ts, text-runner/src/actions/built-in/create-file.ts, text-runner/src/actions/built-in/test.ts, text-runner/src/actions/built-in/verify-source-file-content.ts, text-runner/src/actions/built-in/verify-workspace-contains-directory.ts, text-runner/src/actions/built-in/verify-workspace-file-content.ts, text-runner/src/commands/scaffold.ts, text-runner/text-run/verify-ast-node-attributes.ts, text-runner/text-run/verify-handler-args.ts, textrun-action/src/name-short.ts, textrun-javascript/src/actions/run.ts, textrun-javascript/src/actions/validate.ts, textrun-make/src/actions/command.ts, textrun-make/src/actions/target.ts, textrun-npm/src/actions/install.ts, textrun-shell/src/actions/exec-output.ts, textrun-shell/src/actions/exec-with-input.ts, textrun-shell/src/actions/exec.ts, textrun-shell/src/actions/start-output.ts, textrun-shell/src/actions/start.ts, textrun-shell/src/actions/stop.ts
=> Rename args to action

text-runner/features/configuration-options/keep-tmp.feature, text-runner/src/commands/dynamic.ts, text-runner/src/commands/run.ts, text-runner/src/commands/static.ts, text-runner/src/configuration/cli/parse-cmdline-args.test.ts, text-runner/src/configuration/cli/parse-cmdline-args.ts, text-runner/src/configuration/config-file/load-config-file.ts, text-runner/src/configuration/determine-configuration.ts, text-runner/src/configuration/merge-configurations.test.ts, text-runner/src/configuration/types/configuration.ts, text-runner/src/configuration/types/user-provided-configuration.ts, textrun-extension/src/actions/run-block.ts, textrun-extension/src/actions/run-textrunner.ts, textrun-workspace/features/append-file.feature, textrun-workspace/features/create-directory.feature, textrun-workspace/features/create-file.feature
=> Rename Tmp to workspace

text-runner/src/actions/action-finder.ts, text-runner/src/commands/dynamic.ts, text-runner/src/commands/static.ts
=> Protect internal actions

text-runner/src/parsers/standard-AST/ast-node-list.test.ts, text-runner/src/parsers/standard-AST/ast-node-list.ts, textrun-javascript/README.md, textrun-make/README.md, textrun-npm/README.md, textrun-npm/features/install.feature, textrun-npm/src/actions/install.ts, textrun-repo/README.md, textrun-shell/README.md
=> Correctly handle multi-line paragraph content

README.md, text-runner/src/link-targets/link-target-list.ts, text-runner/src/link-targets/target-url.test.ts, text-runner/src/link-targets/target-url.ts
=> GitHub-compatible anchors

text-runner/src/parsers/html/html-parser.ts, text-runner/src/parsers/markdown/helpers/closing-tag-parser.ts, text-runner/src/parsers/markdown/md-parser.ts, text-runner/src/parsers/standard-AST/ast-node.ts, text-runner/src/parsers/tag-mapper.test.ts, text-runner/src/parsers/tag-mapper.ts
=> use enums for AstNode strings

text-runner/src/parsers/tag-mapper.ts
=> Rename Remarkable to MarkdownIt

text-runner/src/configuration/cli/parse-cmdline-args.ts, text-runner/src/configuration/determine-configuration.test.ts, text-runner/src/configuration/types/user-provided-configuration.ts, text-runner/src/text-runner.ts
=> Enums for commands

documentation/configuration.md, text-runner/features/configuration-file/generate.feature, text-runner/src/configuration/config-file/create-configuration-file.ts, text-runner/src/configuration/config-file/load-config-file.ts, text-runner/src/configuration/determine-configuration.ts, text-runner/src/configuration/types/configuration.ts, text-runner/src/configuration/types/user-provided-configuration.ts
=> Remove Configuration.actions

documentation/package.json, examples/custom-action-async/package.json, examples/custom-action-callback/package.json, examples/custom-action-coffeescript/package.json, examples/custom-action-multiple/package.json, examples/custom-action-promise/package.json, examples/custom-action-sync/package.json, examples/custom-action-typescript/package.json, examples/multiple-returns/package.json, shared/cucumber-steps/package.json
=> Make internal repos private

documentation/package.json, shared/cucumber-steps/package.json, textrun-javascript/package.json
=> Change licenses to ISC

.circleci/config.yml
=> Run all tests in parallel on CircleCI

.circleci/config.yml
=> CircleCI: no yarn cache

.circleci/config.yml, textrun-npm/README.md
=> CircleCI: test only affected code bases

examples/custom-action-async/text-run/hello-world.js, examples/custom-action-callback/text-run/hello-world.js, examples/custom-action-promise/text-run/hello-world.js, examples/custom-action-sync/text-run/hello-world.js, shared/cucumber-steps/src/given-steps.ts
=> Use arguments as namespaces

examples/custom-action-async/text-run/hello-world.js
=> Better timeout

documentation/package.json, textrun-action/package.json, textrun-javascript/package.json, textrun-make/package.json, textrun-npm/package.json, textrun-repo/package.json, textrun-workspace/package.json
=> Add missing dependencies

.circleci/config.yml, textrun-npm/README.md
=> CircleCI: build only involved code bases on feature branches

examples/custom-action-async/Makefile, examples/custom-action-coffeescript/Makefile, examples/custom-action-typescript/Makefile
=> Test docs of examples

text-runner/src/actions/action-finder.test.ts
=> Fix unit tests

Makefile
=> Remove make suppressors

shared/cucumber-steps/src/helpers.test.ts, shared/cucumber-steps/src/helpers.ts
=> Remove unused function

textrun-javascript/src/actions/runnable.ts
=> Print executed JS

shared/cucumber-steps/src/world.ts
=> Remove TODO

textrun-shell/src/actions/command-with-input.ts
=> Reduce redundancy

shared/cucumber-steps/src/env.ts, shared/cucumber-steps/src/given-steps.ts, shared/cucumber-steps/src/then-steps.ts, shared/cucumber-steps/src/world.ts, text-runner/src/actions/built-in/check-image.ts, text-runner/src/actions/built-in/check-link.ts, text-runner/src/commands/scaffold.ts, text-runner/src/configuration/config-file/create-configuration-file.ts, text-runner/src/configuration/config-file/determine-config-filename.ts, text-runner/src/filesystem/has-directory.ts, text-runner/src/filesystem/is-markdown-file.ts, text-runner/src/parsers/html/parse-html-files.ts, text-runner/src/parsers/markdown/parse-markdown-files.ts, textrun-make/src/actions/command.ts, textrun-make/src/actions/target.ts, textrun-repo/src/existing-file.ts, textrun-workspace/src/actions/additional-file-content.ts, textrun-workspace/src/actions/existing-directory.ts
=> WIP: Remove fs-extra

documentation/Makefile, text-runner/Makefile, textrun-action/Makefile, textrun-extension/Makefile, textrun-javascript/Makefile, textrun-make/Makefile, textrun-npm/Makefile, textrun-repo/Makefile, textrun-workspace/Makefile
=> Remove manual cleanup step

Makefile
Make on Windows doesn't silence when the `SILENT` target is present.
=> Silence Make on Windows

Makefile, documentation/Makefile, documentation/configuration.md, text-runner-features/configuration-file/generate.feature, text-runner-features/configuration-options/offline.feature, text-runner-features/formatters/signals.feature, text-runner/Makefile, text-runner/src/actions/built-in/check-image.ts, text-runner/src/actions/built-in/check-link.ts, text-runner/src/commands/help.ts, text-runner/src/configuration/cli/parse-cmdline-args.test.ts, text-runner/src/configuration/cli/parse-cmdline-args.ts, text-runner/src/configuration/config-file/create-configuration-file.ts, text-runner/src/configuration/config-file/load-config-file.ts, text-runner/src/configuration/determine-configuration.ts, text-runner/src/configuration/merge-configurations.test.ts, text-runner/src/configuration/types/configuration.ts, text-runner/src/configuration/types/user-provided-configuration.ts, textrun-action/Makefile, textrun-extension/Makefile, textrun-javascript/Makefile, textrun-make/Makefile, textrun-npm/Makefile, textrun-repo/Makefile, textrun-shell/Makefile, textrun-shell/src/helpers/path-mapper-test.ts, textrun-workspace/Makefile
=> Online option

text-runner/src/configuration/config-file/load-config-file.ts, text-runner/src/configuration/load-configuration.ts
=> Load YML asynchronously

shared/cucumber-steps/package.json, shared/cucumber-steps/src/given-steps.ts, text-runner/package.json, yarn.lock
=> Remove ShellJS

text-runner-features/commands/scaffold-command.feature, text-runner/src/cli.ts, text-runner/src/commands/help.ts, text-runner/src/commands/scaffold.ts, text-runner/src/configuration/cli/parse-cmdline-args.ts, text-runner/src/configuration/types/user-provided-configuration.ts, text-runner/src/helpers/camelize.test.ts, text-runner/src/helpers/camelize.ts
=> Scaffold TypeScript actions

documentation/configuration.md, shared/cucumber-steps/src/then-steps.ts, text-run.yml, text-runner-features/configuration-file/generate.feature, text-runner-features/configuration-options/use-system-tmp-dir.feature, text-runner/src/configuration/cli/parse-cmdline-args.ts, text-runner/src/configuration/config-file/create-configuration-file.ts, text-runner/src/configuration/config-file/load-config-file.ts, text-runner/src/configuration/determine-configuration.ts, text-runner/src/configuration/merge-configurations.test.ts, text-runner/src/configuration/types/configuration.ts, text-runner/src/configuration/types/user-provided-configuration.ts, text-runner/src/working-dir/create-working-dir.ts, text-runner/text-run.yml
=> New configuration option for UseSystemTempDirectory

text-runner-cli/package.json, text-runner-core/package.json
=> Rename make spec to make test

text-runner-cli/Makefile, text-runner-core/Makefile
=> Remove make cuke-ci

.circleci/run-if-affected, .prettierignore, Makefile
=> Optimize make lint and fix

text-runner-core/package.json, text-runner-core/src/actions/action-finder.ts, text-runner-core/src/actions/built-in/check-image.ts, text-runner-core/src/actions/built-in/check-link.ts
=> Remove color

text-runner-cli/package.json, text-runner-cli/src/helpers/stats-collector.test.ts, yarn.lock
=> Remove delay module

documentation/configuration.md, shared/cucumber-steps/src/then-steps.ts, text-runner-cli/src/cmdline.ts, text-runner-cli/src/config-file.ts, text-runner-cli/src/configuration.ts, text-runner-core/src/configuration/data.ts, text-runner-core/src/configuration/defaults.ts, text-runner-core/src/workspace/create.ts, text-runner-features/configuration-file/generate.feature, text-runner-features/configuration-options/empty-workspace.feature
=> Option to not delete the workspace

shared/cucumber-steps/src/then-steps.ts, text-runner-core/src/commands/run.ts, text-runner-features/configuration-options/use-system-tmp-dir.feature
=> Consistent workspace configuration

documentation/configuration.md, text-runner-cli/src/cmdline.ts, text-runner-cli/src/config-file.ts, text-runner-cli/src/configuration.ts, text-runner-core/src/configuration/data.ts, text-runner-core/src/configuration/defaults.ts, text-runner-core/src/run/run-activity.ts, text-runner-features/actions/custom/skipping.feature, text-runner-features/configuration-file/generate.feature, text-runner-features/configuration-options/show-skipped.feature
=> Don't display skipped files

text-runner-cli/src/index.ts
=> Print code frame

text-runner-core/src/filesystem/get-filenames.test.ts, text-runner-core/src/filesystem/get-filenames.ts, text-runner-features/specifying-files/ignoring-workspace.feature
=> Ignore workspace files

text-runner-cli/src/cmdline.ts, text-runner-cli/src/commands/instantiate.ts, text-runner-core/src/ast/node-list.ts, text-runner-core/src/commands/debug.ts, text-runner-core/src/configuration/defaults.ts, text-runner-core/src/errors/user-error.ts, text-runner-core/src/filesystem/get-filenames.ts, text-runner-features/commands/debug-command.feature
=> Enforce guidance

shared/cucumber-steps/src/then-steps.ts, text-runner-features/configuration-options/show-skipped.feature, textrun-extension/features/run-textrunner.feature, textrun-workspace/features/working-dir.feature
=> Always check success

shared/cucumber-steps/src/when-steps.ts
=> Increase test timeout

text-runner-cli/bin/text-run
=> Change starter script to Node

text-runner-cli/.mocharc.json, text-runner-cli/.mocharc.yml, text-runner-core/.mocharc.json, text-runner-core/.mocharc.yml, textrun-extension/.mocharc.json, textrun-extension/.mocharc.yml, textrun-javascript/.mocharc.json, textrun-javascript/.mocharc.yml, textrun-make/.mocharc.json, textrun-make/.mocharc.yml, textrun-npm/.mocharc.json, textrun-npm/.mocharc.yml, textrun-repo/.mocharc.json, textrun-repo/.mocharc.yml, textrun-shell/.mocharc.json, textrun-shell/.mocharc.yml, textrun-workspace/.mocharc.json, textrun-workspace/.mocharc.yml
JSON is just more readable and easier to ensure correctness
=> Convert YML config files to JSON where possible

Makefile, documentation/package.json, examples/custom-action-commonjs/package.json, examples/custom-action-esm/package.json, examples/custom-action-typescript/package.json, examples/global-tool/package.json, package.json, shared/cucumber-steps/package.json, text-runner-cli/package.json, text-runner-core/package.json, textrun-action/package.json, textrun-extension/package.json, textrun-javascript/package.json, textrun-make/package.json, textrun-npm/package.json, textrun-repo/package.json, textrun-shell/package.json, textrun-workspace/package.json, yarn.lock
Rather than using a Prettier plugin. This makes us more independent of Prettier.
=> Use sort-package-json directly

documentation/package.json, documentation/text-runner.jsonc, examples/custom-action-commonjs/package.json, examples/custom-action-esm/package.json, examples/custom-action-typescript/package.json, examples/global-tool/package.json, text-runner-cli/package.json, text-runner-core/package.json, text-runner.jsonc, textrun-action/package.json, textrun-extension/package.json, textrun-javascript/package.json, textrun-make/package.json, textrun-npm/package.json, textrun-repo/package.json, textrun-shell/package.json, textrun-workspace/package.json
The progress formatter leaves traces in the turbo output.
=> Use the dot formatter everywhere

text-runner-cli/src/formatters/dot-formatter.ts, textrun-extension/src/actions/run-textrunner.ts, textrun-extension/src/actions/runnable-region.ts, textrun-workspace/src/actions/existing-file-with-content.ts
Removes the hack that simply dumps everything.
=> Improve output when errors
